name: Build:Main
on:
  push:
    branches: [ main, test-ready ]
jobs:
  build-libraries:
    runs-on: ubuntu-latest
    env:
      CLIENTREPO: ${GITHUB_WORKSPACE}/client
    steps:
    - name: Download zstd
      uses: dsaltares/fetch-gh-release-asset@0.0.5
      with:
        repo: "facebook/zstd"
        version: "tags/v1.4.9"
        file: zstd-1.4.9.tar.gz
    - name: Cache zstd
      id: cache-zstd
      uses: actions/cache@v2
      env:
        cache-name: zstd
      with:
        path: zstd-1.4.9
        key: zstd-1.4.9-${{ runner.os }}
    - name: Build zstd
      id: build-zstd
      if: steps.cache-zstd.outputs.cache-hit != 'true'
      run: |
        tar xvfz zstd-1.4.9.tar.gz && cd zstd-1.4.9
        make
        #make test
    - name: install zstd
      run: |
        cd zstd-1.4.9
        sudo make install
    - name: Checkout c client
      uses: actions/checkout@v2
      with:
        repository: aerospike/aerospike-client-c
        submodules: recursive
        path: client
    - name: Checkout asbackup
      uses: actions/checkout@v2
      with: 
        path: main
        submodules: recursive
    - name: Build client lib
      run: make
      working-directory: client
    - name: Build asbackup
      run: |
        make
        cp -r bin dyn_bin
        make clean
      working-directory: main
    - name: Build asbackup with static link to zstd
      run: |
        make LINK_ZSTD_STATIC=1
        cp -r bin static_bin
        make clean
      working-directory: main
    - name: Upload asbackup artifact
      uses: actions/upload-artifact@v2
      with: 
        name: asbackup
        path: main/dyn_bin/asbackup
        if-no-files-found: error
    - name: Upload asrestore artifact
      uses: actions/upload-artifact@v2
      with: 
        name: asrestore
        path: main/dyn_bin/asrestore
        if-no-files-found: error
    - name: Upload static zstd asbackup artifact
      uses: actions/upload-artifact@v2
      with: 
        name: asbackup-libzstd-static
        path: main/static_bin/asbackup
        if-no-files-found: error
    - name: Upload static zstd asrestore artifact
      uses: actions/upload-artifact@v2
      with: 
        name: asrestore-libzstd-static
        path: main/static_bin/asrestore
        if-no-files-found: error
  pre-release:
    needs: build-libraries
    runs-on: ubuntu-latest

    steps: 
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3.1

      - name: Checkout asbackup
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with: 
          path: binaries/
      - name: Create tarball
        run: tar -czf binaries.tar.gz binaries
      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Snapshot Build"
          files: |
            binaries.tar.gz
            LICENSE.md
            README.md
